### ISSUE TITLE
Asymetric Encryption / Decryption

### ISSUE THREAD

**Issue by paulwoelfelcpl** [googleapis/nodejs-kms#104]
Currently the Node.JS library of Cloud KMS only supports encryption and decryption using symmetric keys. Any plans to also implement the [GetPublicKey](https://cloud.google.com/kms/docs/reference/rpc/google.cloud.kms.v1#google.cloud.kms.v1.KeyManagementService.GetPublicKey) and [AsymmetricDecrypt](https://cloud.google.com/kms/docs/reference/rpc/google.cloud.kms.v1#keymanagementservice) Methods of GRPC like in [python](https://cloud.google.com/kms/docs/encrypt-decrypt-rsa#kms-howto-encrypt-rsa-python)?

**Comment by paulwoelfelcpl** [comment]
Just noticed, that it's already in the master branch. Is there a plan, when this will be released?

**Comment by kinwa91** [comment]
It's release via v0.3.0, sorry for the delay!
