### ISSUE TITLE
FAILED_PRECONDITION : Google Cloud KMS API has not been used in this project before

### ISSUE THREAD

**Issue by brunorzn** [googleapis/nodejs-kms#179]
I've created a new project on Google Cloud Platform.

On this project, I've enabled the KMS Api, and created a key-ring, and a key.

I've also created a service account with the roles : Cloud KMS CryptoKey Encrypter/Decrypter, and set everything in my code.

When I try to access the API, it errors with status "FAILED_PRECONDITION" and message :

"Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."

Note that the given url failed when I open it.

When I use previous credentials (old project, old service account, but exact same configuration), everything works fine.

When I try to access the API via the Google Api Explorer, the error is the same.

**Comment by callmehiphop** [comment]
@brunorzn I would double check that you haven't skipped a step on our [quickstart](https://github.com/googleapis/nodejs-kms#quickstart) guide.

**Comment by brunorzn** [comment]
Thank you for your answer.

Unfortunately, I don't think I've skipped any step :

1 - the project is created
2 - the billing is enabled for this project
3 - the KMS Api is enabled for this project
4 - the service account is set up

I wasn't using the GOOGLE_APPLICATION_CREDENTIALS environment variable, but even when I'm using it it's the same result.

I've just tried with the sample you provided on the quickstart guide, and I have the exact same error. I have trie creating a service account with project>owner privileges, but, again, same result.

Also, I can see my requests in the API metrics from GCP, with 100% errors.

**Comment by callmehiphop** [comment]
@stephenplusplus any thoughts on this?

**Comment by JustinBeckwith** [comment]
@brunorzn can you share an example of the code you're using?

**Comment by brunorzn** [comment]
Yes. The code from the _quickstart_, given that GOOGLE_APPLICATION_CREDENTIALS is correctly set : 

`async function quickstart(
  projectId = 'your-project-id' // Your GCP projectId
) {
  // Imports the @google-cloud/kms client library
  const kms = require('@google-cloud/kms');

  // Instantiates an authorized client
  const client = new kms.KeyManagementServiceClient();

  // Lists keys in the "global" location.
  const locationId = 'global';

  // Lists key rings
  const parent = client.locationPath(projectId, locationId);
  const [keyRings] = await client.listKeyRings({parent});

  // Display the results
  if (keyRings.length) {
    console.log('Key rings:');
    keyRings.forEach(keyRing => console.log(keyRing.name));
  } else {
    console.log(`No key rings found.`);
  }
}`

**Comment by brunorzn** [comment]
Again, this behavior  seems to occur when I'm using new projects (I've created two today), not when I use an older project.

**Comment by brunorzn** [comment]
I've opened an issue on Google Issue Tracker : https://issuetracker.google.com/issues/135209265

Here are simple steps to reproduce  (maybe I'm forgetting something ?) 

1 - create new project on google cloud console
2 - in this project, go to Security > Cryptographic Keys and enable billing / API
3 - go to API Explorer

for instance : https://developers.google.com/apis-explorer/#search/kms/cloudkms/v1/cloudkms.projects.locations.keyRings.get

and type in "name" input field : "projects/{YOUR_PROJECT_ID}}/locations/global/keyRings", then Execute.

Response : 

```
{
 "error": {
  "code": 400,
  "message": "Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=XXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
  "status": "FAILED_PRECONDITION"
 }
}
```

Note that the given url failed to load.

**Comment by brunorzn** [comment]
I've retried today and the problem seems to be fixed.

I have no further explanation, but eh, at least it works !

Closing it.

**Comment by callmehiphop** [comment]
@brunorzn thanks for the update! Glad it works, sorry we couldn't get it resolved sooner

**Comment by scott45** [comment]
Hey guys, Getting the same issue on an existing project that I'm contributing to. I enabled the KMS API but whenever I try to create a keyring, I get _**"Google Cloud KMS API has not been used in this project before, or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudkms.googleapis.com/overview?project=xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."**_

**Comment by scott45** [comment]
Okay, thanks @bcoe
