### ISSUE TITLE
encrypt/decrypt sample arguments do not match request types

### ISSUE THREAD

**Issue by brandonrodriguez** [googleapis/nodejs-kms#221]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-kms/issues *done*
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node *done*
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js *done*

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows
  - Node.js version: 10.15.3
  - npm version: 6.9.2
  - `@google-cloud/kms` version: 1.3.0

#### Steps to reproduce

  1. The documentation on Google Cloud [1] and in encrypt.js [2] note that EncryptRequest.plaintext should be of type `bytes`.
  2. The documentation on Google Cloud [1] and in decrypt.js [3] note that DecryptRequest.ciphertext should be of type `bytes`.
  3. When using "@types/google-cloud__kms": "^1.3.0", TypeScript complains when passing a String to the encrypt() and decrypt() methods, and nudges to use a Buffer.

Should the samples be updated to use Buffers instead of Strings for `plaintext` and `ciphertext`? e.g., `Buffer.from(contentsBuffer.toString('base64'))` instead of `contentsBuffer.toString('base64')`

**Comment by brandonrodriguez** [comment]
Forgot my citations.
[1] https://cloud.google.com/kms/docs/reference/rpc/google.cloud.kms.v1
[2] https://github.com/googleapis/nodejs-kms/blob/master/samples/encrypt.js
[3] https://github.com/googleapis/nodejs-kms/blob/master/samples/decrypt.js

**Comment by bcoe** [comment]
@brandonrodriguez thanks for the bug report. @alexander-fenster any thoughts on why this might be generating with the wrong types for the methods in question? I imagine this might be something we need to fix in the proto files?

**Comment by alexander-fenster** [comment]
This is fixed in the new TypeScript generator. The generated code for KMS will have `Buffer` in jsdoc documentation. The library will be updated soon.

Example here (we have KMS as one of our baseline tests so you can take a look how it will be after migration to TypeScript):

https://github.com/googleapis/gapic-generator-typescript/blob/cac5ca489dde4adbee7942ff93dd0f8ed3b614f7/typescript/test/testdata/keymanager/src/v1/key_management_service_client.ts.baseline#L1078
