### ISSUE TITLE
Support for asymmetric sign

### ISSUE THREAD

**Issue by raman-nbg** [googleapis/nodejs-kms#239]
Currently the nodjs client library does not support using KMS asymmetric signing.

https://cloud.google.com/kms/docs/reference/rpc/google.cloud.kms.v1#google.cloud.kms.v1.AsymmetricSignRequest

Are there any plans to support this feature?

**Comment by raman-nbg** [comment]
It seems like that this feature is already implemented, but not tested or documented.

Is this feature already safe to use?

**Comment by bcoe** [comment]
@raman-nbg our libraries are largely auto-generated, and the upstream KMS library is a v1 API.

All this is to say, yes this feature is safe to use :+1:

We should definitely consider adding a sample for it CC: @jkwlui.

**Comment by raman-nbg** [comment]
Thank you for adding an example. The exported types also do not contain a definition for asymmetricSign(): https://www.npmjs.com/package/@types/google-cloud__kms

Of course I can use this by type casting to `any`. But this makes it hard to use this with TypeScript.

**Comment by bcoe** [comment]
@raman-nbg these types are not part of this project, and I believe are community contributed. We are in the process of converting our libraries to TypeScript (@alexander-fenster perhaps we could prioritize KMS?) at which point the types for `asymmetricSign` will be available.
