### ISSUE TITLE
Fails to resolve GRPC endoint when called from GKE pod

### ISSUE THREAD

**Issue by LibertyBeta** [googleapis/nodejs-kms#381]
#### Environment details

  - OS: Debian inside K8s pod
  - Node.js version: 10.15
  - npm version: 6.4.1
  - `@google-cloud/kms` version:2.1.2

#### Steps to reproduce

  1. Deployed pod with mounted certificate
  2. Make a client with said certificate
  3. Attempt to use any function of the client.

The following error will be produced: `"The GRPC target is not implemented on the server, host: secretmanager.googleapis.com, method: /google.cloud.kms.v1.KeyManagementService/Decrypt." ` with the final GRPC method being the issue.

NOTE: The cert was tested locally and works correctly, and works for its other IAM scopes. Also, the code in question is being called from a handler for a gRPC server, if that's any help. OpenTelemetry is also running in the process as well.

**Comment by sofisl** [comment]
Hi there! Would you mind including a snippet of your code to reproduce? Thanks in advance.

**Comment by sethvargo** [comment]
This Q is also posted on StackOverflow at https://stackoverflow.com/questions/63696633/google-cloud-platform-kms-fails-to-resolve-grpc-endoint-when-called-from-gke-pod

That endpoint is incorrect. It should be cloudkms.googleapis.com.

**Comment by LibertyBeta** [comment]
@sofisl Sure thing. 
```
import { SecretManagerServiceClient } from "@google-cloud/secret-manager"; // used in other function in the file, included in case it affects things
import { KeyManagementServiceClient } from "@google-cloud/kms";
const config = {
    keyFilename: "valid key location with tested key",
};
....
async function decryptSecret(secret: string): Promise<string> {
    try {
        const kms = new KeyManagementServiceClient(config);
        const keyName = kms.cryptoKeyPath(
            process.env.PROJECT,
            process.env.CLUSTER_LOCATION,
            process.env.KEYRING,
            "disco"
        );
        logger.info(keyName); // This resolves to the correct resouce
        const [result] = await kms.decrypt({
            name: keyName,
            ciphertext: secret,
        });

        return result.plaintext.toString();
    } catch (e) {
        logger.error("failed to decrypt");
        logger.error(e);
        return "";
    }
}
```

@sethvargo The Stack is me, figured I would cast a wide net. And yeah, I'm befuddled as to why I'm getting THIS grpc error, but only when in the k8s pod. Same code works otherwise.

**Comment by sethvargo** [comment]
Does it go away if you remove the import for Secret Manager? I wonder if the endpoint is somehow being clobbered when the state is shared.

/cc @bcoe

**Comment by LibertyBeta** [comment]
So, splitting the imports/functions into two separate files did fix it. Think this might be a real bug.

**Comment by sethvargo** [comment]
> splitting the imports/functions into two separate files did fix it.

Can you clarify - separate files or separate modules?

**Comment by LibertyBeta** [comment]
Two separate modules, even if they are both always imported together.

**Comment by bcoe** [comment]
@LibertyBeta I was able to reproduce your issue using your thorough example:

```js
import { SecretManagerServiceClient } from "@google-cloud/secret-manager"; // used in other function in the file, included in case it affects things
import { KeyManagementServiceClient } from "@google-cloud/kms";
const config = {
    keyFilename: "valid key location with tested key",
};
```

The smoking gun is the shared `config` object, this file is being mutated by the first client, then breaking the second client.

We are working on a fix right now.

**Comment by LibertyBeta** [comment]
Ah, awesome. I'll keep an eye out for it then. Glad I could help sniff out a bug.
